Access/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("Company.urls")),
    path("", include("Authentication.urls")),
    path("", include("Employee.urls")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

Employee/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("singleemp/<int:group_id>/", views.SingleEmpView, name="employee"),
    path("jobs", views.Alljobsview, name="jobs"),
    path("signupemp", views.SignUpEmpView, name="signupemp"),
    path("profileemp/<int:pro_id>/", views.ProfileEmpView, name="profileemp"),
    path("registerexp/<int:pro_id>/", views.RegisterExpView, name="registerexp"),





]

Company/models.py
from django.db import models
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.utils.text import slugify
from django.apps import apps
import datetime

# Create your models here.


class Company(models.Model):
    name = models.CharField(max_length=100)

    image = models.ImageField(upload_to="images/", null=True)
    

    street = models.CharField(max_length=80, null=True)
    postal_code = models.CharField(max_length=5, null=True)
    city = models.CharField(max_length=50, null=True)

    description = models.TextField(max_length=2000)



    contanct_number = models.CharField(max_length=100)
    feild = models.CharField(max_length=200, null=True)
    date = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True)
    author = models.EmailField(max_length=100, null=False)

    slug = models.SlugField(default="", blank=True, null=False, db_index=True)

    # relations
    def get_absolute_url(self):
        return reverse("company", args=[self.id])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Company, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} ({self.contanct_number})"


class Job(models.Model):
    title = models.CharField(max_length=100)

    description = models.TextField(max_length=2000)
    type = models.CharField(max_length=500, null=True)
    slug = models.SlugField(default="", blank=True, null=False, db_index=True)
    feild = models.CharField(max_length=200, null=True)
    order= models.IntegerField(null=True)
    # relations
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    Main_skill = models.ManyToManyField("Employee.Main_skill")
    Employees = models.ManyToManyField("Employee.Employee", blank=True)

    def get_absolute_url(self):
        return reverse("SingleJob", args=[self.id])

    def __str__(self):
        return f"{self.title} ({self.company.name})"
    

Employee/models.py
from django.db import models
from django.urls import reverse
import datetime
# from Company.models import Company


from django.utils.text import slugify


# Create your models here.
class Main_skill(models.Model):
    name = models.CharField(max_length=80)
    description = models.CharField(max_length=500, null=True)

    def __str__(self):
        return f"{self.name}"




class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    image = models.ImageField(upload_to="images/", null=True)

    street = models.CharField(max_length=80, null=True)
    postal_code = models.CharField(max_length=5, null=True)
    city = models.CharField(max_length=50, null=True)

    description = models.TextField(max_length=2000)
    Dob = models.DateField(auto_now=False, auto_now_add=False)
    contanct_number = models.CharField(max_length=100)
    feild = models.CharField(max_length=200, null=True)
    author = models.EmailField(max_length=100, null=False)

    slug = models.SlugField(default="", blank=True, null=False, db_index=True)
    order=models.IntegerField(null=True)

    # relations
    Main_skills = models.ManyToManyField(Main_skill)

    def get_absolute_url(self):
        return reverse("employee", args=[self.id])

    def __str__(self):
        return f"{self.first_name} ({self.last_name})"



class Exp(models.Model):
    title = models.CharField(max_length=80)
    description = models.TextField(max_length=2000, null=True)
    start_date = models.DateField(
        auto_now=False, auto_now_add=False, null=True, blank=True
    )
    end_date = models.DateField(
        auto_now=False, auto_now_add=False, default=datetime.date.today()
    )
    company = models.CharField(max_length=500)
    type = models.CharField(max_length=500, null=True)
    feild = models.CharField(max_length=200, null=True)

    # relations
    Main_skills = models.ManyToManyField(Main_skill)
    
    emp = models.ForeignKey(Employee ,on_delete=models.CASCADE, default="5")

    def __str__(self):
        return f"{self.title}"

Employee/forms.py
from django import forms

from .models import Employee


class SignUpEmpForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"
        exclude = ["author"]

Employee/views.py
from django.contrib.messages import constants as messages
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Employee, Main_skill, Exp
from Company.models import Job,Company
from django.shortcuts import render, redirect


# filling the employee data


def SignUpEmpView(request):
    main = Main_skill.objects.all()

    fill_relations = {"main": main, }

    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")

        street = request.POST.get("street")
        postal_code = request.POST.get("postal_code")
        city = request.POST.get("city")

        image = request.FILES.get("image")

        description = request.POST.get("description")
        Dob = request.POST.get("Dob")
        contanct_number = request.POST.get("contanct_number")

        feild = request.POST.get("feild")
        if 'SoftwareEngineering'in feild:
            feild="software engineering"
        elif 'ArchitectureEngineering'in feild:
            feild="Architecture Engineering"    
        elif 'Businessfield'in feild:
            feild="Business Field" 
        skills = request.POST.getlist("skills")

        my_emp = Employee.objects.create(
            first_name=first_name,
            last_name=last_name,
            image=image,
            street=street,
            city=city,
            postal_code=postal_code,
            description=description,
            Dob=Dob,
            contanct_number=contanct_number,
            feild=feild,
            author=request.user.username,
        )
        my_emp.Main_skills.set(skills)

        my_emp.save()
        return redirect("jobs")


    return render(request, "Employee/SignUpEmp.html", fill_relations)

# displaying all jobs related to each employee


def Alljobsview(request):
    employee = Employee.objects.filter(author=request.user.username).first()
    if request.method == "POST":
        jobs = Job.objects.filter(title__contains=request.POST.get("form-control me-2"))
    if request.method == "GET":
        jobs = Job.objects.all()
        

        x=0
        for job in jobs:
            for skill in job.Main_skill.all():
                if skill in employee.Main_skills.all():
                    x=x+1
                if skill not in employee.Main_skills.all():
                    x=x-1

            job.order=x

            job.save()

            
                    
        jobs = Job.objects.order_by('-order')


    fill_relations = {"employee": employee, "jobs": jobs}
    return render(request, "Employee/Jobs.html", fill_relations)

# displaying single employee profile

def SingleEmpView(request, group_id):
    context = Company.objects.filter(author=request.user.username).first()
    employee = Employee.objects.filter(id=group_id).first()
    experience= Exp.objects.filter(emp=employee).all()

    if context is None:
        context = Employee.objects.filter(author=request.user.username).first()
        if context.id==employee.id:
            return redirect('profileemp',pro_id=group_id)

    
    

    fill_relations = {"employee": employee, "context": context,"experience":experience}
    return render(request, "Employee/SingleEmp.html", fill_relations)

def ProfileEmpView(request, pro_id):
    context = Employee.objects.filter(author=request.user.username).first()
    employee = Employee.objects.filter(id=pro_id).first()
    experience= Exp.objects.filter(emp=employee).all()

    fill_relations = {"employee": employee, "context": context,"experience":experience}
    return render(request, "Employee/profileemp.html", fill_relations)

def RegisterExpView(request,pro_id):
    context = Employee.objects.filter(author=request.user.username).first()   
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        start_date = request.POST.get("start_date")
        end_date = request.POST.get("end_date")


        type = request.POST.get("type")
        company = request.POST.get("company")
        skills = request.POST.getlist("skills")




        my_Exp= Exp.objects.create(
            title=title,
            company=company,
            description=description,
            type=type,
            emp=context,
            start_date=start_date,
            end_date=end_date,
        )
        my_Exp.Main_skills.set(skills)

        my_Exp.save()
        return redirect('profileemp',pro_id=pro_id)
    company = Company.objects.all()

    fill_relations = {"companys": company, "context": context}
    return render(request, "Employee/RegisterExp.html", fill_relations)

Employee/templates/Employee/RegisterExp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    Register Job
  </title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
  <!--Stylesheet-->
  <link href="https://unpkg.com/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://unpkg.com/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'css/singleemp.css' %}">
</head>

<body>
    <section style="background-color: #eee;">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
          <div class="container-fluid">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="brand">
                  <a class="nav-link active" aria-current="page" href="#"><b>access</b></a>
                </li>
                <li class="brand">
                  <a class="nav-link" href="{% url 'jobs' %}">Home</a>
                </li>
                <li class="brand">
                  <a class="nav-link" href="{% url 'companys' %}">Companies</a>
                </li>
              </ul>
              <div class="form_control">
    
            </div>
            {% if context.last_name%}
            <p class="name">{{ context.first_name }}
            {{context.last_name }}</p>
            {% else %}
            <p class="name">{{ context.name }}</p>
        {% endif %}
    
            <img class="img_nav" src="{{ context.image.url}}" alt="Paris" width="40px" height="40px" >
          </div>
        </nav>
        <div class="container py-5" style="margin-left:290px">
            {% comment %} <div class="row">
              <div class="col">
                
              </div>
            </div> {% endcomment %}
        
            <div class="row">

                <form method="POST" class="row g-3 needs-validation" > 
                    {% csrf_token %}
              </div>
              <div class="col-lg-8">
                <div class="card mb-4">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-sm-3">
                        <p class="mb-0">Job Title</p>
                      </div>
                      <div class="col-sm-9">
                        <input type="text"  name="title" id="title"class="form-control" required>

                    </div>
                    </div>
                  
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <p class="mb-0">Job type</p>
                      </div>
                      <div class="col-sm-9">
                        <select class="form-select" aria-label="Default select example"id="type"name="type" required>
                          <option value="Full Time"selected>Full Time</option>
                          <option value="Part Time">Part Time</option>
                          <option value="Remotely">Remotely</option>
                        </select>
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <p class="mb-0">Start Date</p>
                      </div>
                      <div class="col-sm-9">
                        <input type="date" name="start_date"class="form-control" required id="start_date">
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <p class="mb-0">end Date</p>
                    </div>
                    <div class="col-sm-9">
                      <input type="date" name="end_date"class="form-control" required id="end_date">
                  </div>
                </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <p class="mb-0">Gained Skills </p>
                      </div>
                      <div class="col-sm-9">
                        <select class="form-control" id="skills" name='skills'multiple>
                          {% for skill in context.Main_skills.all %}
                              <option value='{{skill.id}}'>{{ skill.name }}</option>
                          {% endfor %}
                      </select>
                    </div>
                  </div>
                      <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <p class="mb-0">Description</p>
                      </div>
                      <div class="col-sm-9">
                        <textarea class="form-control"required  name="description" maxlength="500" required id="description" style="height: 100px"></textarea >
                         
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <p class="mb-0">Comapny</p>
                      </div>
                      <div class="col-sm-9">
                        <input list="company" name="company">
                          <datalist id="company" name="company">
                            {% for company in companys %}
                          <option value='{{company.name}}'>{{ company.name }}</option>
                        {% endfor %}
                           
                      </div>
                    </div>
                  </div>
                </div>



              <button type="submit" class="btn btn-primary btn-lg" style="margin-left:770px">Register</button>
                    
                </form>
                    {% comment %} <hr> {% endcomment %}
      
                    {% comment %} <div class="row">
                      <div class="col-sm-3">
                        <p class="mb-0">Openings</p>
                      </div>
                      <div class="col-sm-9">
                        {% for job in jobs%}
                          <button type="button" class="btn btn-primary">{{job.title}}</button>
                        
            
                      {% endfor %}  
            
                      </div> {% endcomment %}
                    </div>
                  </div>


    
</body>
</html> 

Employee/templates/Employee/SignUpEmp.html
<!DOCTYPE html>
<html lang="en">
{% csrf_token %}
{% load static %}


<head>
    <title>Signup Page</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Signemp.css' %}"/>


</head>
<style>


.filterDiv {

    color: black;

    display: none;
  }
  
  .show {
    display: block;
  }



</style>
<body style="display: flex; justify-content: space-around;">
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>

    
    <form method="POST" enctype="multipart/form-data" class="row g-3" style="margin-top:50px;margin-bottom:50px">
        {% csrf_token %}
        <h3>Sign Up Here</h3>
        
        <div class="col-md-6">
            <label for="inputEmail4" class="form-label">First name</label>
            <input type="text" class="form-control" id="first_name"name="first_name">
          </div>
          <div class="col-md-6">
            <label for="inputPassword4" class="form-label">Last Name</label>
            <input type="text" class="form-control" id="last_name"name="last_name">
          </div>

          <div class="col-md-6">
            <label for="inputCity" class="form-label">Address</label>
            <input type="text" class="form-control" id="street" placeholder="1234 Main St" name="street">
          </div>
          <div class="col-md-4">
            <label for="inputState" class="form-label">city</label>
            <input type="text" class="form-control" id="city"name="city">

          </div>
          <div class="col-md-2">
            <label for="inputZip" class="form-label">Zip</label>
            <input type="text" class="form-control" id="inputZip"name="postal_code">
          </div>
          
          </div>
          


    <div class="fieldWrapper">
        
        <label for="id_description"class="form-label">Description:</label> <textarea class="form-control"  name="description" maxlength="500" required id="description" style="height: 100px"></textarea >
        
    </div>
    <div class="fieldWrapper">
        
        <label for="id_image">Image:</label>   <input type="file" class="form-control" id="inputGroupFile01" name="image">

        
    </div>

    <div class="col-md-4">
        
        <label for="id_Dob"class="form-label">Dob:</label> <input type="date" name="Dob"class="form-control" required id="Dob">
        
    </div>

    <div class="col-md-4">
        
        <label for="id_contanct_number"class="form-label">Contanct number:</label> <input type="text"class="form-control" name="contanct_number" maxlength="100" required id="contanct_number"placeholder="01XXXXXXXXX">
        
    </div>

    <div class="col-md-4">
        
        <label for="id_contanct_number"class="form-label">Feild:</label> 
        <select class="form-select" aria-label="Default select example" name="feild"onchange="filterSelection(value);">
            <option value="SoftwareEngineering"class="btn" onclick="filterSelection('SoftwareEngineering')"selected>Software Engineering</option>
            <option value="ArchitectureEngineering"class="btn" onclick="filterSelection('MechanicalEngineering')">Architecture Engineering</option>
            <option value="Businessfield"class="btn" onclick="filterSelection('Businessfield')">Business Field</option>
          </select>
    </div>


    <div class="col-md-6">
        
        <label for="id_Main_skill">Main skill:</label> <select class="form-control" id="skills" name='skills'multiple >
            {% for skill in main %}
                <option value='{{skill.id}}' class="filterDiv {{ skill.description }}">{{ skill.name }}</option>
            {% endfor %}
        </select>
        
    </div>

    {% comment %} <div class="col-md-6">
        
        <label for="id_Pluses">Pluses:</label> <select name="pluse" required id="pluse" multiple>
            {% for pluse in plus %}
            <option value='{{pluse.id}}'>{{ pluse.name }}</option>
        {% endfor %}

</select> {% endcomment %}
        
    </div>

        <button type="submit">Send</button>

        {% if img_obj %}  
        <h3>Succesfully uploaded : {{img_obj.caption}}</h3>  
        <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">  
    {% endif %}  
  
</body>
<script>
    filterSelection("all")
    function filterSelection(c) {
      var x, i;
      x = document.getElementsByClassName("filterDiv");
      if (c == "all") c = "";
      for (i = 0; i < x.length; i++) {
        w3RemoveClass(x[i], "show");
        if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
      }
    }
    
    function w3AddClass(element, name) {
      var i, arr1, arr2;
      arr1 = element.className.split(" ");
      arr2 = name.split(" ");
      for (i = 0; i < arr2.length; i++) {
        if (arr1.indexOf(arr2[i]) == -1) {element.className += " " + arr2[i];}
      }
    }
    
    function w3RemoveClass(element, name) {
      var i, arr1, arr2;
      arr1 = element.className.split(" ");
      arr2 = name.split(" ");
      for (i = 0; i < arr2.length; i++) {
        while (arr1.indexOf(arr2[i]) > -1) {
          arr1.splice(arr1.indexOf(arr2[i]), 1);     
        }
      }
      element.className = arr1.join(" ");
    }
    
    // Add active class to the current button (highlight it)
    var btnContainer = document.getElementById("myBtnContainer");
    var btns = btnContainer.getElementsByClassName("btn");
    for (var i = 0; i < btns.length; i++) {
      btns[i].addEventListener("click", function(){
        var current = document.getElementsByClassName("active");
        current[0].className = current[0].className.replace(" active", "");
        this.className += " active";
      });
    }
    </script>
</html>

Employee/templates/Employee/SingleEmp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {{ employee.first_name }} {{ employee.last_name }}
  </title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
  <!--Stylesheet-->
  <link href="https://unpkg.com/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://unpkg.com/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'css/singleemp.css' %}">
</head>
<body>
    {% comment %} <h1>{{ employee.first_name }}</h1>
    

    <p>{{ employee.first_name }}</p>
    <p>{{ employee.description }}</p>
    {% for w in employee.Main_skill.all %}
  <tr>
    <td>{{ w }}</td>
  </tr>
  {% endfor %}
  <br>

  {% for w in employee.experience_set.all %}
  <tr>
    <td>{{ w.title }}</td>
  </tr>
  <p>
    <p>
  {% endfor %} {% endcomment %}
  
  <section style="background-color: #eee;">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container-fluid">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="brand">
              <a class="nav-link active" aria-current="page" href="#"><b>access</b></a>
            </li>
            <li class="brand">
              {% if context.last_name%}
              <a class="nav-link" href="{% url 'jobs' %}">Home</a>

        {% else %}
        <a class="nav-link" href="{% url 'home_com' %}">Home</a>
        {% endif %}             </li>
            <li class="brand">
              <a class="nav-link" href="{% url 'companys' %}">Companies</a>
            </li>
          </ul>
          <div class="form_control">

        </div>
        
        {% if context.last_name%}
        <p class="name">{{ context.first_name }}
        {{context.last_name }}</p>
        {% else %}
        <p class="name">{{ context.name }}</p>
    {% endif %}
        <img class="img_nav" src="{{ context.image.url}}" alt="Paris" width="40px" height="40px" >
      </div>
    </nav>
    <div class="container py-5">
      <div class="row">
        <div class="col">
          
        </div>
      </div>
  
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
              <img src="{{ employee.image.url }}"
                class="rounded-circle img-fluid" style="width: 150px;">
              <h5 class="my-3">{{ employee.first_name }} {{ employee.last_name }}</h5>
              <p class="text-muted mb-1">{{ employee.feild }}</p>
              <p class="text-muted mb-4">{{ employee.street }},{{ employee.city }},{{ employee.postal_code }}</p>
              <div class="d-flex justify-content-center mb-2">

              </div>
            </div>
          </div>

        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Full Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ employee.first_name }} {{ employee.last_name }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ employee.author }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ employee.contanct_number }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Description</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ employee.description }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Address</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ employee.street }},{{ employee.city }},{{ employee.postal_code }}</p>
                </div>
              </div>
              <hr>

              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Skills</p>
                </div>
                <div class="col-sm-9">
                  {% for skill in employee.Main_skills.all%}
                    <button type="button" class="btn btn-primary">{{skill.name}}</button>
                  
      
                {% endfor %}  
      
                </div>
              </div>
            </div>
          </div>
          <div class="row">

          </div>

            <div class="col-md-6">
              <div class="row">
            
              </div>
            </div>

                <h5>Past Experiance</h5>

        <div class="card mb-6">

    <div class="card-body">
        
        

      {% for exp in experience%}
  {% comment %} <div class="css-1i76nwa"> {% endcomment %}
    <div style="display: flex;">
    <strong>{{ exp.title }}</strong><div class="type"> {{exp.type}}</div></div>
  <div class="row">
    <div class="col-10">
      <p>{{ exp.company }} </p>
         
         <p> <b>From</b> {{ exp.start_date }} <b>To</b> {{ exp.end_date }}</p> 
         <span style="white-space: pre-wrap;">{{ exp.description }}</span><br><br>




  

</div>



</div>

</div>

  {% endfor %}
     
  </div> 
             
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
</html>